#pragma once

#define ANSI_YELLOW  "\x1b[33m"
#define ANSI_BRIGHT_YELLOW  "\x1b[93m"
#define ANSI_RED     "\x1b[31m"
#define ANSI_RED_BG  "\x1b[101m"
#define ANSI_GREEN   "\x1b[32m"
#define ANSI_BLUE    "\x1b[34m"
#define ANSI_BLACK    "\x1b[30m"
#define ANSI_VIOLET  "\x1b[1;35m"
#define ANSI_CYAN    "\x1b[1;36m"
#define ANSI_RESET   "\x1b[0m"
#define ERROR_STR    ANSI_RESET "[" ANSI_RED "ERROR" ANSI_RESET "]"

#define SHELL_RED "\e[0;31m"
#define SHELL_LIGHT_RED "\e[1;31m"
#define SHELL_GREEN "\e[0;32m"
#define SHELL_BLUE "\e[0;34m"
#define SHELL_LIGHT_BLUE "\e[1;34m"
#define SHELL_YELLOW "\e[1;33m"
#define SHELL_LIGHT_PURPLE "\e[1;35m"
#define SHELL_RESET "\e[0m"
#define SHELL_LIGHT_GREY "\e[0;37m"
#define SHELL_CYAN "\e[0;36m"
#define SHELL_LIGHT_CYAN "\e[1;36m"
#define SHELL_BROWN "\e[0;33m"
